name: Deploy app to server

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/be-images:latest
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop apiContainer
            docker rm apiContainer
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/be-images:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/be-images:latest
            docker run -d -p 80:8080 -e secrets.DBUSER=${{ secrets.DBUSER }} -e secrets.DBPASS=${{ secrets.DBPASS }} -e secrets.DBHOST=${{ secrets.DBHOST }} -e secrets.DBPORT=${{ secrets.DBPORT }} -e secrets.DBNAME=${{ secrets.DBNAME }} -e secrets.JWTSECRET=${{ secrets.JWTSECRET }} --name apiContainer airbnbProject/be-images:latest
          
